apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: napp
  replicas: 2
  template:
    metadata:
      labels:
        app: napp
    spec:
      containers:
      - name: napp
        image: nginx
        ports:
        - containerPort: 80
